apiVersion: v1
kind: Secret
metadata:
  name: quickshop-secret
  namespace: quickshop
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cXVpY2tzaG9w      # echo -n 'quickshop' | base64
  SPRING_DATASOURCE_PASSWORD: cXVpY2tzaG9w       # echo -n 'quickshop' | base64
  MYSQL_ROOT_PASSWORD: cm9vdA==              # echo -n 'root' | base64
  MYSQL_USER: cXVpY2tzaG9w
  MYSQL_PASSWORD: cXVpY2tzaG9w
  APP_JWT_SECRET: WTJWaloyeGxMV3AzZEMxclpYa3RabTl5TFhGeGRYbHphRzl3TFRRNU1qWXRVMmxuYm1GblFTMUpNalkyTFZOcFoyNXBibWN0UVMxa01qTXlOVFkzT0RrNE9BPT0=
  #SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG: <base64>
  # value: org.apache.kafka.common.security.plain.PlainLoginModule required username="<key>" password="<secret>";
  GF_SECURITY_ADMIN_USER: YWRtaW4=
  GF_SECURITY_ADMIN_PASSWORD: YWRtaW4=