apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  namespace: quickshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: quickshop-service-registry:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8761
          envFrom:
            - configMapRef:
                name: quickshop-config
            - secretRef:
                name: quickshop-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: service-registry
  namespace: quickshop
spec:
  selector:
    app: service-registry
  ports:
    - port: 8761
      targetPort: 8761